Repository qiskit-community/qiskit-optimization, pull requests merged in 2021-08, with the labels that each got.

#197 Fix the link to the release note of Qiskit optimization
  CONTRIBUTING.md
Labels: automerge

#220 Bump reno requirement to latest version and set default_branch
  releasenotes/config.yaml
  requirements-dev.txt
Labels: automerge, stable backport potential

#223 Override classmethod supports_aux_operators in VQEProgram
  qiskit_optimization/runtime/vqe_program.py
  test/algorithms/test_min_eigen_optimizer.py
Labels: stable backport potential

#208 application: Sherrington Kirkpatrick (SK) model
  .pylintdict
  qiskit_optimization/applications/__init__.py
  qiskit_optimization/applications/sk_model.py
  releasenotes/notes/sk-model-851851e42be88cc4.yaml
  test/applications/test_sk_model.py
Labels: Changelog: New feature, automerge

#231 Fix lint errors
  qiskit_optimization/applications/max_cut.py
  qiskit_optimization/applications/tsp.py
  qiskit_optimization/problems/quadratic_program.py
  qiskit_optimization/version.py
  test/problems/test_quadratic_program.py
  tools/extract_deprecation.py
  tools/generate_spell_dict.py
Labels: priority: high, stable backport potential, type: bug

#233 Fix docs release notes search
  .github/workflows/deploy-docs.yml
  .github/workflows/main.yml
  Makefile
Labels: priority: high, type: documentation

#234 [Stable] Fix docs release notes search (#233)
  .github/workflows/deploy-docs.yml
  .github/workflows/main.yml
  Makefile
Labels: priority: high, type: documentation

#230 Fix `IntegerToBinary` converter with quadratic terms and zero range variables
  qiskit_optimization/converters/integer_to_binary.py
  releasenotes/notes/fix-int2bin-a998f31885d3b9d8.yaml
  test/converters/test_converters.py
Labels: Changelog: Bugfix, stable backport potential, automerge

#240 [Stable] Add Windows/Mac to CI (#236)
  .github/actions/install-libraries/action.yml
  .github/actions/install-main-dependencies/action.yml
  .github/actions/install-optimization/action.yml
  .github/actions/run-tests/action.yml
  .github/workflows/deploy-docs.yml
  .github/workflows/main.yml
  test/algorithms/test_cplex_optimizer.py
  test/problems/test_quadratic_program.py
  tools/check_copyright.py
  tools/extract_deprecation.py
  tools/generate_spell_dict.py
Labels: type: enhancement, type: ci
