Repository qiskit-community/qiskit-optimization, pull requests merged in 2021-11, with the labels that each got.

#275 Break symmetry of op_mip1.lp
  test/algorithms/resources/op_ip3.lp
  test/algorithms/resources/op_mip1.lp
  test/algorithms/test_cplex_optimizer.py
  test/algorithms/test_gurobi_optimizer.py
  test/algorithms/test_recursive_optimization.py
Labels: stable backport potential, automerge

#274 Remove the deprecated `QuadraticProgram.{from_docplex,to_docplex}`
  qiskit_optimization/problems/quadratic_program.py
  releasenotes/notes/remove-deprecated-docplex-2981d40bc957cd47.yaml
  test/problems/test_quadratic_program.py
Labels: Changelog: API Change, automerge

#277 Convert issue templates to GitHub forms
  .github/ISSUE_TEMPLATE/BUG_REPORT.md
  .github/ISSUE_TEMPLATE/BUG_REPORT.yaml
  .github/ISSUE_TEMPLATE/ENHANCEMENT_REQUEST.md
  .github/ISSUE_TEMPLATE/ENHANCEMENT_REQUEST.yaml
  .github/ISSUE_TEMPLATE/FEATURE_REQUEST.md
  .github/ISSUE_TEMPLATE/FEATURE_REQUEST.yaml
Labels: type: enhancement

#282 Update Mergify to remove deprecation
  .mergify.yml
Labels: automerge, type: ci

#284 Fix latest pylint errors and mergify automerge
  .github/workflows/main.yml
  .mergify.yml
  qiskit_optimization/problems/substitute_variables.py
Labels: priority: high, type: bug
