Repository qiskit-community/qiskit-optimization, pull requests merged in 2021-06, with the labels that each got.

#45 Interface for Gurobi through the gurobipy API
  .github/actions/install-optimization/action.yml
  .github/workflows/main.yml
  .pylintdict
  .pylintrc
  README.md
  docs/getting_started.rst
  qiskit_optimization/algorithms/__init__.py
  qiskit_optimization/algorithms/gurobi_optimizer.py
  qiskit_optimization/problems/quadratic_program.py
  releasenotes/notes/add-gurobipy-94f45e32abb61c7b.yaml
  setup.py
  test/algorithms/test_gurobi_optimizer.py
  test/problems/test_quadratic_program.py
Labels: Changelog: New feature

#154 Fixed link to bib file in README
  README.md
Labels: automerge

#155 Update docplex version
  requirements.txt
Labels: automerge

#156 Fix unused imports
  qiskit_optimization/converters/quadratic_program_converter.py
  test/problems/test_quadratic_program.py
Labels: automerge

#160 Docs - Remove non overidden base methods/attributes from classes
  docs/_templates/autosummary/class.rst
Labels: type: documentation

#122 Adds translators between modeling libraries and quadratic program
  .pylintdict
  docs/tutorials/01_quadratic_program.ipynb
  docs/tutorials/04_grover_optimizer.ipynb
  docs/tutorials/05_admm_optimizer.ipynb
  docs/tutorials/06_examples_max_cut_and_tsp.ipynb
  docs/tutorials/08_cvar_optimization.ipynb
  docs/tutorials/10_warm_start_qaoa.ipynb
  qiskit_optimization/algorithms/cplex_optimizer.py
  qiskit_optimization/algorithms/gurobi_optimizer.py
  qiskit_optimization/applications/clique.py
  qiskit_optimization/applications/exact_cover.py
  qiskit_optimization/applications/graph_partition.py
  qiskit_optimization/applications/knapsack.py
  qiskit_optimization/applications/max_cut.py
  qiskit_optimization/applications/number_partition.py
  qiskit_optimization/applications/set_packing.py
  qiskit_optimization/applications/stable_set.py
  qiskit_optimization/applications/tsp.py
  qiskit_optimization/applications/vehicle_routing.py
  qiskit_optimization/applications/vertex_cover.py
  qiskit_optimization/problems/quadratic_program.py
  qiskit_optimization/translators/__init__.py
  qiskit_optimization/translators/docplex_mp.py
  qiskit_optimization/translators/gurobipy.py
  releasenotes/notes/add-model-translators-11e7f3b53574afa7.yaml
  test/algorithms/test_admm.py
  test/algorithms/test_grover_optimizer.py
  test/algorithms/test_gurobi_optimizer.py
  test/algorithms/test_min_eigen_optimizer.py
  test/algorithms/test_warm_start_qaoa.py
  test/converters/test_converters.py
  test/problems/test_quadratic_program.py
  test/translators/__init__.py
  test/translators/test_docplex_mp.py
  test/translators/test_gurobi.py
Labels: Changelog: New feature, priority: high

#162 Remove unused logger
  qiskit_optimization/algorithms/cplex_optimizer.py
  qiskit_optimization/algorithms/gurobi_optimizer.py
  qiskit_optimization/algorithms/recursive_minimum_eigen_optimizer.py
  qiskit_optimization/algorithms/slsqp_optimizer.py
  qiskit_optimization/converters/inequality_to_equality.py
  qiskit_optimization/converters/integer_to_binary.py
  test/algorithms/test_cobyla_optimizer.py
  test/converters/test_converters.py
Labels: automerge

#161 Add deprecation method template
  qiskit_optimization/algorithms/admm_optimizer.py
  qiskit_optimization/deprecation.py
  qiskit_optimization/problems/quadratic_program.py
  test/algorithms/test_admm.py
  test/problems/test_quadratic_program.py
  test/test_deprecation.py
  test/translators/test_gurobi.py
Labels: type: enhancement

#115 #110 Raised ValueError if trials <= 0
  qiskit_optimization/algorithms/multistart_optimizer.py
  test/algorithms/test_cobyla_optimizer.py
Labels: automerge

#170 Remove TYPE_CHECKING flag from code
  docs/apidocs/qiskit_optimization.translators.rst
  qiskit_optimization/__init__.py
  qiskit_optimization/problems/quadratic_program.py
  qiskit_optimization/translators/docplex_mp.py
  qiskit_optimization/translators/gurobipy.py
Labels: automerge, type: documentation

#163 Add indicator constraint support in `from_docplex_mp` translator
  qiskit_optimization/translators/docplex_mp.py
  releasenotes/notes/add-indicator-constraint-071b54d9ae1b042f.yaml
  test/problems/test_quadratic_program.py
  test/translators/test_docplex_mp.py
Labels: Changelog: New feature, priority: high

#166 Separate `from_ising` and `to_ising` out from `QuadraticProgram`
  .pylintdict
  qiskit_optimization/problems/quadratic_program.py
  qiskit_optimization/translators/__init__.py
  qiskit_optimization/translators/ising.py
  releasenotes/notes/add-ising-translator-b93e22adda321e56.yaml
  test/translators/test_ising.py
Labels: Changelog: New feature

#172 Improvements to deprecate methods
  .pylintdict
  qiskit_optimization/deprecation.py
  test/test_deprecation.py
Labels: type: enhancement

#176 Add type ignore for numpy 1.21
  qiskit_optimization/algorithms/admm_optimizer.py
Labels: priority: critical

#174 Refactor converters and `MinimumEigenOptimizer`
  qiskit_optimization/algorithms/grover_optimizer.py
  qiskit_optimization/algorithms/minimum_eigen_optimizer.py
  qiskit_optimization/algorithms/optimization_algorithm.py
  qiskit_optimization/applications/optimization_application.py
  qiskit_optimization/converters/flip_problem_sense.py
  qiskit_optimization/converters/inequality_to_equality.py
  qiskit_optimization/converters/integer_to_binary.py
  qiskit_optimization/converters/linear_equality_to_penalty.py
  qiskit_optimization/converters/quadratic_program_to_qubo.py
  qiskit_optimization/problems/quadratic_objective.py
  releasenotes/notes/min-eigen-opt-order-9e030bb2d8d63656.yaml
Labels: Changelog: API Change, automerge

#178 Suppress Gurobi message when `disp==False` and add the missing model update
  qiskit_optimization/algorithms/gurobi_optimizer.py
  qiskit_optimization/translators/gurobipy.py
  test/translators/test_gurobi.py
Labels: automerge

#165 Separate `SubstituteVariable` out from `QuadraticProgram`
  .pylintdict
  qiskit_optimization/problems/quadratic_program.py
  qiskit_optimization/problems/substitute_variables.py
  test/algorithms/test_warm_start_qaoa.py
  test/problems/test_quadratic_program.py
  test/problems/test_substitute_variables.py
Labels: automerge

#182 Move away from using pylint header plugin & new deprecate_values decorator
  .github/workflows/main.yml
  .pylintdict
  .pylintrc
  Makefile
  qiskit_optimization/deprecation.py
  requirements-dev.txt
  test/test_deprecation.py
  tools/verify_headers.py
  tox.ini
Labels: type: enhancement

#181 Revert `_should_define_penalty` of `LinearEqualityToPenalty`
  qiskit_optimization/converters/linear_equality_to_penalty.py
  test/converters/test_converters.py
Labels: automerge, priority: high

#185 Fix a warning by pylint 2.9.0
  qiskit_optimization/algorithms/warm_start_qaoa_optimizer.py
Labels: priority: critical
