Repository qiskit-community/qiskit-optimization, pull requests merged in 2021-07, with the labels that each got.

#187 Preparing docs & tutorials for translations
  .github/workflows/deploy-docs.yml
  docs/_templates/versions.html
  docs/conf.py
  docs/versionutils.py
  tools/deploy_translatable_strings.sh
  tools/github_poBranch_update_key.enc
  tox.ini
Labels: type: documentation

#188 [Stable] Add Getting Started Documentation & Prepare doc & tutorials for translations
  .github/workflows/deploy-docs.yml
  README.md
  constraints.txt
  docs/_templates/versions.html
  docs/conf.py
  docs/custom_directives.py
  docs/getting_started.rst
  docs/index.rst
  docs/versionutils.py
  qiskit_optimization/algorithms/admm_optimizer.py
  qiskit_optimization/algorithms/warm_start_qaoa_optimizer.py
  requirements-dev.txt
  tools/deploy_translatable_strings.sh
  tools/github_poBranch_update_key.enc
  tox.ini
Labels: type: documentation

#190 Getting started: fix typo
  docs/getting_started.rst
Labels: automerge, type: documentation

#169 Add lower bound and upper bound of `LinearExpression` and `QuadraticExpression`
  qiskit_optimization/converters/inequality_to_equality.py
  qiskit_optimization/converters/linear_equality_to_penalty.py
  qiskit_optimization/problems/linear_expression.py
  qiskit_optimization/problems/quadratic_expression.py
  qiskit_optimization/problems/quadratic_program.py
  releasenotes/notes/add-bounds-expressions-3eeb6d3c06414b31.yaml
  test/problems/test_linear_expression.py
  test/problems/test_quadratic_expression.py
Labels: Changelog: New feature, automerge

#167 QAOA runtime program
  .pylintdict
  docs/apidocs/qiskit_optimization.runtime.rst
  qiskit_optimization/__init__.py
  qiskit_optimization/runtime/__init__.py
  qiskit_optimization/runtime/qaoa_program.py
  qiskit_optimization/runtime/vqe_program.py
  releasenotes/notes/qaoa-runtime-307e2aebc9e715a2.yaml
  test/runtime/__init__.py
  test/runtime/fake_vqeruntime.py
  test/runtime/test_qaoaprogram.py
  test/runtime/test_vqeprogram.py
Labels: Changelog: New feature

#191 Fixed typos
  qiskit_optimization/__init__.py
  qiskit_optimization/problems/quadratic_program.py
Labels: automerge, type: documentation

#192 Fix `QuadraticProgramElement` when in-place copy of `QuadraticProgram`
  qiskit_optimization/problems/quadratic_program.py
  test/converters/test_converters.py
  test/problems/test_quadratic_program.py
Labels: automerge

#193 Revises reno
  qiskit_optimization/algorithms/cplex_optimizer.py
  releasenotes/notes/add-cplex-params-2b7bd7bde01400c7.yaml
  releasenotes/notes/add-gurobipy-94f45e32abb61c7b.yaml
  releasenotes/notes/add-indicator-constraint-071b54d9ae1b042f.yaml
  releasenotes/notes/add-ising-translator-b93e22adda321e56.yaml
  releasenotes/notes/add-model-translators-11e7f3b53574afa7.yaml
  releasenotes/notes/fix-bit-ordering-e807ec9f4b206ec3.yaml
  releasenotes/notes/fix-empty-obj-3a99dc67c319806d.yaml
  releasenotes/notes/fix-grover-rotation-count-853baefc6b7e8476.yaml
  releasenotes/notes/fix-gw-0c0cd70d0aa44a2e.yaml
  releasenotes/notes/maximize-to-minimize-58cd1cbd752ed382.yaml
Labels: automerge, type: documentation

#157 Special patterns of inequality constraint to penalty converters
  .pylintdict
  qiskit_optimization/converters/__init__.py
  qiskit_optimization/converters/linear_inequality_to_penalty.py
  qiskit_optimization/converters/quadratic_program_to_qubo.py
  releasenotes/notes/linear-inequality-to-penalty-70b5277b8edda012.yaml
  test/converters/test_linear_inequality_to_penalty.py
Labels: Changelog: New feature, automerge

#199 Pin networkx
  requirements.txt
Labels: priority: critical, stable backport potential, type: bug

#196 Updating the translation deploy script
  docs/conf.py
  tools/deploy_translatable_strings.sh
Labels: stable backport potential

#205 Streamline CI
  .github/workflows/main.yml
Labels: type: ci, type: enhancement

#206 [Stable] Streamline CI (#205)
  .github/workflows/main.yml
Labels: type: ci, type: enhancement

#207 Add link to repo tutorial on html tutorial prolog
  README.md
  docs/conf.py
  docs/getting_started.rst
Labels: automerge, stable backport potential, type: documentation, type: enhancement

#203 Remove random_graph method from GraphOptimizationApplication
  qiskit_optimization/applications/graph_optimization_application.py
Labels: automerge

#195 fixed broken link to code of conduct
  CODE_OF_CONDUCT.md
Labels: automerge

#183 Add a tutorial of translators and classical optimization solvers
  .pylintdict
  docs/tutorials/11_using_classical_optimization_solvers_and_models.ipynb
Labels: automerge

#214 Allow Qiskit Optimizers in the runtime programs
  qiskit_optimization/runtime/qaoa_program.py
  qiskit_optimization/runtime/vqe_program.py
  releasenotes/notes/runtime-optimizers-58f30311f969f54f.yaml
  test/runtime/fake_vqeruntime.py
  test/runtime/test_qaoaprogram.py
  test/runtime/test_vqeprogram.py
Labels: Changelog: Bugfix, automerge, stable backport potential
