Repository qiskit-community/qiskit-optimization, pull requests merged in 2021-04, with the labels that each got.

#69 Fix Doc Theme Errors
  .github/workflows/deploy-docs.yml
  docs/_static/style.css
  docs/_templates/autosummary/base.rst
  docs/_templates/autosummary/class.rst
  docs/_templates/autosummary/module.rst
  docs/_templates/layout.html
  docs/_templates/page.html
  docs/_templates/theme_variables.jinja
  docs/conf.py
  docs/index.rst
  docs/tutorials/_static/custom.css
  docs/tutorials/_static/gallery.css
  requirements.txt
Labels: stable backport potential, type: bug

#70 [Stable] Fix Doc Theme Errors
  .github/workflows/deploy-docs.yml
  docs/_static/style.css
  docs/_templates/autosummary/base.rst
  docs/_templates/autosummary/class.rst
  docs/_templates/autosummary/module.rst
  docs/_templates/layout.html
  docs/_templates/page.html
  docs/_templates/theme_variables.jinja
  docs/conf.py
  docs/index.rst
  docs/tutorials/_static/custom.css
  docs/tutorials/_static/gallery.css
  requirements.txt
Labels: type: bug

#71 Remove decorator from requirements, added during its buggy period
  requirements.txt
Labels: stable backport potential

#73 Mergify: configuration update
  .mergify.yml
Labels: stable backport potential, type: enhancement

#75 Disable Conan on CI Aer build
  .github/actions/install-master-dependencies/action.yml
Labels: priority: high, stable backport potential, type: bug

#83 Add reno/config.yaml
  releasenotes/config.yaml
Labels: automerge, stable backport potential

#85 Make sure CI gets Qiskit dependencies from pypi on stable
  .github/workflows/main.yml
Labels: automerge, stable backport potential, type: bug

#89 Prepare for renaming default branch to main
  .github/actions/install-main-dependencies/action.yml
  .github/workflows/main.yml
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README.md
  docs/tutorials/07_examples_vehicle_routing.ipynb
  qiskit_optimization/version.py
  tox.ini
Labels: stable backport potential

#96 Fix unit test of GroverOptimizer
  qiskit_optimization/algorithms/grover_optimizer.py
  test/algorithms/test_grover_optimizer.py
Labels: stable backport potential

#87 [Stable] Make sure CI gets Qiskit dependencies from pypi on stable (#85)
  .github/workflows/main.yml
Labels: type: bug

#102 Fix lint msgs caused by latest pylint release
  qiskit_optimization/version.py
  test/problems/test_quadratic_program.py
  tools/check_copyright.py
Labels: priority: high, stable backport potential, type: bug

#107 Print PendingDeprecation warnings in the CI
  .github/actions/run-tests/action.yml
  .github/workflows/main.yml
Labels: type: ci
