Repository qiskit-community/qiskit-optimization, pull requests merged in 2021-09, with the labels that each got.

#242 Install Terra under conda environment for Windows CI
  .github/actions/install-main-dependencies/action.yml
Labels: type: bug, type: ci

#243 [Stable] Install Terra under conda for Windows CI (#242)
  .github/actions/install-main-dependencies/action.yml
Labels: type: bug, automerge, type: ci

#244 Fix CPLEX parameters for unit tests
  test/algorithms/test_cplex_optimizer.py
  test/algorithms/test_min_eigen_optimizer.py
  test/algorithms/test_recursive_optimization.py
  test/converters/test_converters.py
Labels: stable backport potential, automerge

#247 Improve project setup long-description
  README.md
  setup.py
Labels: type: documentation, type: enhancement

#249 Fix Miniconda CI Windows install
  .github/actions/install-main-dependencies/action.yml
  .github/actions/install-optimization/action.yml
  .github/actions/run-tests/action.yml
  .github/workflows/main.yml
Labels: priority: high, type: bug, type: ci

#250 [Stable] Fix Miniconda CI Windows install (#249)
  .github/actions/install-main-dependencies/action.yml
  .github/actions/install-optimization/action.yml
  .github/actions/run-tests/action.yml
  .github/workflows/main.yml
Labels: automerge

#251 Disable pylint consider-using-f-string for now
  .pylintrc
Labels: priority: high, type: bug

#254 Re-enable lint f-string check
  .pylintrc
  README.md
  qiskit_optimization/algorithms/admm_optimizer.py
  qiskit_optimization/algorithms/grover_optimizer.py
  qiskit_optimization/algorithms/optimization_algorithm.py
  qiskit_optimization/applications/clique.py
  qiskit_optimization/applications/exact_cover.py
  qiskit_optimization/applications/graph_partition.py
  qiskit_optimization/applications/knapsack.py
  qiskit_optimization/applications/max_cut.py
  qiskit_optimization/applications/number_partition.py
  qiskit_optimization/applications/optimization_application.py
  qiskit_optimization/applications/set_packing.py
  qiskit_optimization/applications/stable_set.py
  qiskit_optimization/applications/tsp.py
  qiskit_optimization/applications/vehicle_routing.py
  qiskit_optimization/applications/vertex_cover.py
  qiskit_optimization/converters/integer_to_binary.py
  qiskit_optimization/converters/linear_equality_to_penalty.py
  qiskit_optimization/converters/quadratic_program_to_qubo.py
  qiskit_optimization/deprecation.py
  qiskit_optimization/problems/constraint.py
  qiskit_optimization/problems/quadratic_expression.py
  qiskit_optimization/translators/gurobipy.py
  qiskit_optimization/version.py
  test/converters/test_converters.py
  test/converters/test_flip_problem_sense.py
  test/optimization_test_case.py
  test/problems/test_linear_expression.py
  test/problems/test_quadratic_expression.py
  test/test_readme_sample.py
  tools/check_copyright.py
  tools/extract_deprecation.py
  tools/generate_spell_dict.py
  tools/verify_headers.py
Labels: type: qa

#259 Fix test_recursive_warm_qaoa for CI of windows
  test/algorithms/resources/op_ip3.lp
  test/algorithms/test_recursive_optimization.py
Labels: stable backport potential, automerge

#257 Duck-type VQE interim results
  qiskit_optimization/runtime/vqe_program.py
Labels: automerge
