Repository qiskit-community/qiskit-optimization, pull requests merged in 2021-12, with the labels that each got.

#258 Create bin_packing.py
  qiskit_optimization/applications/__init__.py
  qiskit_optimization/applications/bin_packing.py
  releasenotes/notes/add-bin-packing-app-c4ecf62fe047d496.yaml
  test/applications/test_bin_packing.py
Labels: Changelog: New feature, automerge

#285 Increase tutorials timeout
  docs/conf.py
Labels: priority: high, automerge, type: ci

#289 Temporary Remove Python 3.6 from CI
  .github/workflows/main.yml
Labels: priority: high, type: ci

#291 CI - Run python 3.6 unit test using Terra 0.19 from Pypi
  .github/workflows/main.yml
Labels: type: ci

#292 Fix minor grammar and formatting issues in README and getting_started
  README.md
  docs/getting_started.rst
Labels: automerge

#293 Fix formatting & grammar in 01_quadratic_program tutorial
  docs/tutorials/01_quadratic_program.ipynb
Labels: stable backport potential, automerge

#295 Update garrison's name in .mailmap
  .mailmap
Labels: automerge

#298 Fix `GroverOptimizer` with Aer#1388
  qiskit_optimization/algorithms/grover_optimizer.py
Labels: priority: high

#288 QAOA runtime
  .pylintdict
  docs/tutorials/12_qaoa_runtime.ipynb
  qiskit_optimization/runtime/qaoa_client.py
  qiskit_optimization/runtime/qaoa_program.py
  qiskit_optimization/runtime/vqe_client.py
  releasenotes/notes/qaoa-runtime-client-afa2453fc325d9bd.yaml
  test/algorithms/test_min_eigen_optimizer.py
  test/runtime/fake_vqeruntime.py
  test/runtime/test_qaoaprogram.py
  test/runtime/test_vqeprogram.py
Labels: Changelog: New feature, priority: high, automerge

#180 Enable some mypy options
  mypy.ini
  qiskit_optimization/converters/inequality_to_equality.py
  test/applications/test_bin_packing.py
Labels: type: enhancement
