Repository qiskit-community/qiskit-optimization, pull requests merged in 2021-05, with the labels that each got.

#118 Add missing black settings
  pyproject.toml
  qiskit_optimization/algorithms/admm_optimizer.py
  qiskit_optimization/algorithms/goemans_williamson_optimizer.py
  qiskit_optimization/algorithms/grover_optimizer.py
  qiskit_optimization/algorithms/minimum_eigen_optimizer.py
  qiskit_optimization/algorithms/multistart_optimizer.py
  qiskit_optimization/algorithms/optimization_algorithm.py
  qiskit_optimization/algorithms/recursive_minimum_eigen_optimizer.py
  qiskit_optimization/algorithms/slsqp_optimizer.py
  qiskit_optimization/algorithms/warm_start_qaoa_optimizer.py
  qiskit_optimization/applications/exact_cover.py
  qiskit_optimization/applications/graph_optimization_application.py
  qiskit_optimization/applications/graph_partition.py
  qiskit_optimization/applications/knapsack.py
  qiskit_optimization/applications/max_cut.py
  qiskit_optimization/applications/number_partition.py
  qiskit_optimization/applications/set_packing.py
  qiskit_optimization/applications/tsp.py
  qiskit_optimization/applications/vehicle_routing.py
  qiskit_optimization/converters/inequality_to_equality.py
  qiskit_optimization/converters/integer_to_binary.py
  qiskit_optimization/converters/linear_equality_to_penalty.py
  qiskit_optimization/converters/quadratic_program_to_qubo.py
  qiskit_optimization/problems/linear_expression.py
  qiskit_optimization/problems/quadratic_expression.py
  qiskit_optimization/problems/quadratic_objective.py
  qiskit_optimization/problems/quadratic_program.py
  test/algorithms/test_admm.py
  test/algorithms/test_grover_optimizer.py
  test/algorithms/test_min_eigen_optimizer.py
  test/algorithms/test_recursive_optimization.py
  test/applications/test_clique.py
  test/applications/test_exact_cover.py
  test/applications/test_graph_partition.py
  test/applications/test_knapsack.py
  test/applications/test_set_packing.py
  test/applications/test_stable_set.py
  test/applications/test_tsp.py
  test/applications/test_vehicle_routing.py
  test/converters/test_converters.py
  test/optimization_test_case.py
  test/problems/test_linear_constraint.py
  test/problems/test_linear_expression.py
  test/problems/test_quadratic_constraint.py
  test/problems/test_quadratic_expression.py
  test/problems/test_quadratic_objective.py
  test/problems/test_quadratic_program.py
  test/test_readme_sample.py
  tools/check_copyright.py
  tools/extract_deprecation.py
Labels: type: qa

#119 Insert actual path to source when generating docs
  docs/conf.py
Labels: type: documentation

#120 Add git blame ignore file
  .git-blame-ignore-revs
  CONTRIBUTING.md
Labels: type: qa

#121 Fix sphinx CI Error
  .github/workflows/deploy-docs.yml
  .github/workflows/main.yml
Labels: automerge, priority: high, stable backport potential, type: ci

#125 [Stable] Fix sphinx CI Error (#121)
  .github/workflows/deploy-docs.yml
  .github/workflows/main.yml
Labels: type: ci

#126 Pin sphinx version below 4.0.0
  .github/workflows/deploy-docs.yml
  .github/workflows/main.yml
  requirements-dev.txt
Labels: priority: high

#127 Remove redundant installs from CI
  .github/workflows/deploy-docs.yml
  .github/workflows/main.yml
Labels: type: ci

#97 Fix bit ordering and probabilities of samples in optimization_algorithm.py
  .pylintdict
  qiskit_optimization/algorithms/grover_optimizer.py
  qiskit_optimization/algorithms/optimization_algorithm.py
  qiskit_optimization/problems/quadratic_program.py
  releasenotes/notes/fix-bit-ordering-e807ec9f4b206ec3.yaml
  test/algorithms/test_grover_optimizer.py
  test/algorithms/test_min_eigen_optimizer.py
Labels: Changelog: Bugfix, stable backport potential

#132 Fix GroverOptimizer's rotation_count
  qiskit_optimization/algorithms/grover_optimizer.py
  releasenotes/notes/fix-grover-rotation-count-853baefc6b7e8476.yaml
  test/algorithms/test_grover_optimizer.py
Labels: Changelog: Bugfix, stable backport potential

#136 Adjust random_seed for test_samples_qaoa
  test/algorithms/test_min_eigen_optimizer.py
Labels: automerge

#139 Revise CplexOptimizer
  qiskit_optimization/algorithms/cplex_optimizer.py
  releasenotes/notes/add-cplex-params-2b7bd7bde01400c7.yaml
  test/algorithms/test_cplex_optimizer.py
Labels: Changelog: New feature, automerge

#141 Add Getting Started Documentation
  README.md
  docs/conf.py
  docs/custom_directives.py
  docs/getting_started.rst
  docs/index.rst
  requirements-dev.txt
Labels: type: documentation

#64 Apply spell check to tutorials
  Makefile
  docs/Makefile
  docs/conf.py
  docs/spelling_wordlist.txt
  requirements-dev.txt
Labels: automerge

#140 Raise an appropriate error if an empty objective function is used
  qiskit_optimization/problems/quadratic_objective.py
  releasenotes/notes/fix-empty-obj-3a99dc67c319806d.yaml
  test/problems/test_quadratic_program.py
Labels: Changelog: Bugfix, automerge

#142 Merge spelling dictionaries into one single .pylintdict file
  .pylintdict
  docs/conf.py
  docs/lowercase_filter.py
  docs/spelling_wordlist.txt
  docs/tutorials/10_warm_start_qaoa.ipynb
  tools/generate_spell_dict.py
Labels: type: documentation

#145 Remove _build & stubs dir before running sphinx
  docs/Makefile
  tools/generate_spell_dict.py
Labels: type: documentation

#148 Remove Backend Deprecate Messages
  docs/tutorials/06_examples_max_cut_and_tsp.ipynb
  docs/tutorials/08_cvar_optimization.ipynb
  test/algorithms/test_grover_optimizer.py
Labels: type: enhancement

#149 Run tutorials from stable branch
  .github/workflows/main.yml
  Makefile
  docs/Makefile
Labels: type: ci
