Repository qiskit-community/qiskit-optimization, pull requests merged in 2022-12, with the labels that each got.

#441 Fix deprecation
  qiskit_optimization/runtime/__init__.py
  qiskit_optimization/runtime/qaoa_program.py
  qiskit_optimization/runtime/vqe_program.py
  releasenotes/notes/remove-vqe-qaoa-programs-152a997734296fe2.yaml
  requirements.txt
  test/applications/test_sk_model.py
  test/runtime/test_qaoaprogram.py
  test/runtime/test_vqeprogram.py
Labels: automerge

#450 Raise an error if `VQE` is given to `MinimumEigenOptimizer`
  qiskit_optimization/algorithms/minimum_eigen_optimizer.py
  test/algorithms/test_min_eigen_optimizer.py
Labels: automerge

#451 Update `GroverOptimizer` with Sampler
  qiskit_optimization/algorithms/grover_optimizer.py
  qiskit_optimization/algorithms/optimization_algorithm.py
  test/algorithms/test_grover_optimizer.py
Labels: automerge

#454 Fix CI Aer install
  .github/actions/install-main-dependencies/action.yml
Labels: stable backport potential, automerge, type: ci

#457 Update tox configuration file for tox 4.0.2
  tox.ini
Labels: stable backport potential, type: ci
