Repository qiskit-community/qiskit-optimization, pull requests merged in 2022-02, with the labels that each got.

#327 Fix `seed_simulator` and `seed_transpiler` of `TestRecursiveMinEigenOptimizer`
  test/algorithms/test_recursive_optimization.py
Labels: stable backport potential

#316 Improve wording in tutorials/03_minimum_eigen_optimizer
  docs/tutorials/03_minimum_eigen_optimizer.ipynb
Labels: stable backport potential, automerge

#331 Use code from README.md in test_readme_sample
  README.md
  test/test_readme_sample.py
Labels: stable backport potential, type: enhancement, type: ci

#333 Fix up to_ising docstring
  qiskit_optimization/translators/ising.py
Labels: stable backport potential, type: documentation, automerge

#335 [Stable] Prepare 0.3.1 release
  qiskit_optimization/VERSION.txt
Labels: automerge

#336 Fix some API references
  qiskit_optimization/converters/inequality_to_equality.py
  qiskit_optimization/problems/quadratic_program.py
  qiskit_optimization/problems/substitute_variables.py
  qiskit_optimization/translators/docplex_mp.py
  qiskit_optimization/translators/gurobipy.py
Labels: stable backport potential, automerge

#338 Preparing to publish Bengali docs
  docs/versionutils.py
Labels: stable backport potential, type: documentation

#340 Exclude locale from the sync path
  tools/deploy_documentation.sh
Labels: stable backport potential, type: documentation, automerge
