Repository qiskit-community/qiskit-optimization, pull requests merged in 2022-11, with the labels that each got.

#428 Fix f-string error in the constructor of `OptimizationResult`
  qiskit_optimization/algorithms/optimization_algorithm.py
Labels: automerge

#430 Remove sphinx_rtd_theme from CI
  .github/workflows/deploy-docs.yml
  .github/workflows/main.yml
Labels: automerge, type: ci

#434 Add Spanish to language switcher
  docs/versionutils.py
Labels: stable backport potential

#438 Ignore untagged reno notes on documentation
  tools/ignore_untagged_notes.sh
Labels: stable backport potential, automerge, type: ci

#440 remove ENHANCEMENT_REQUEST issue template
  .github/ISSUE_TEMPLATE/ENHANCEMENT_REQUEST.yaml
Labels: automerge

#443 Update docs to use new sphinx theme
  .github/workflows/main.yml
  docs/_templates/layout.html
  docs/conf.py
  requirements-dev.txt
Labels: stable backport potential, type: documentation

#445 Pin temporarily docplex < 2.24.231
  requirements.txt
Labels: priority: high, type: bug, type: ci

#446 unpin docplex
  requirements.txt
Labels: automerge
