Repository qiskit-community/qiskit-optimization, pull requests merged in 2022-03, with the labels that each got.

#342 Bump black version and relax constraint
  docs/tutorials/06_examples_max_cut_and_tsp.ipynb
  docs/tutorials/07_examples_vehicle_routing.ipynb
  docs/tutorials/08_cvar_optimization.ipynb
  docs/tutorials/12_qaoa_runtime.ipynb
  qiskit_optimization/algorithms/grover_optimizer.py
  qiskit_optimization/algorithms/optimization_algorithm.py
  qiskit_optimization/converters/integer_to_binary.py
  qiskit_optimization/converters/linear_equality_to_penalty.py
  qiskit_optimization/problems/quadratic_expression.py
  requirements-dev.txt
  test/algorithms/test_admm.py
  test/translators/test_docplex_mp.py
Labels: type: enhancement

#343 Adopt lazy imports from Terra
  qiskit_optimization/algorithms/cplex_optimizer.py
  qiskit_optimization/algorithms/goemans_williamson_optimizer.py
  qiskit_optimization/algorithms/gurobi_optimizer.py
  qiskit_optimization/applications/bin_packing.py
  qiskit_optimization/applications/graph_optimization_application.py
  qiskit_optimization/optionals.py
  qiskit_optimization/problems/quadratic_program.py
  qiskit_optimization/translators/gurobipy.py
  requirements.txt
  test/__init__.py
  test/algorithms/test_cplex_optimizer.py
  test/algorithms/test_goemans_williamson_optimizer.py
  test/algorithms/test_gurobi_optimizer.py
  test/algorithms/test_min_eigen_optimizer.py
  test/algorithms/test_recursive_optimization.py
  test/algorithms/test_warm_start_qaoa.py
  test/applications/test_bin_packing.py
  test/applications/test_max_cut.py
  test/converters/test_converters.py
  test/optimization_test_case.py
  test/problems/test_quadratic_program.py
  test/translators/test_gurobi.py
Labels: type: enhancement, run_slow

#344 Preparing to publish Japanese docs
  docs/versionutils.py
Labels: stable backport potential, automerge

#350 Unpin Jinja2
  requirements-dev.txt
Labels: stable backport potential, type: documentation, automerge

#352 Prepare 0.3.2 release
  qiskit_optimization/VERSION.txt
Labels: automerge

#353 Add apply fixes to copyright checker
  .github/workflows/main.yml
  tools/check_copyright.py
Labels: type: enhancement, type: qa, type: ci
