Repository qiskit-community/qiskit-optimization, pull requests merged in 2022-01, with the labels that each got.

#301 Fix mypy errors created with latest numpy
  qiskit_optimization/algorithms/admm_optimizer.py
  qiskit_optimization/algorithms/grover_optimizer.py
  qiskit_optimization/applications/exact_cover.py
  qiskit_optimization/applications/set_packing.py
Labels: priority: high, stable backport potential, type: bug, automerge, type: ci

#304 Remove unnecessary Union with PauliSumOp
  qiskit_optimization/problems/quadratic_program.py
  qiskit_optimization/translators/ising.py
Labels: automerge

#303 Fix one more list in tutorials/05_admm_optimizer.ipynb
  docs/tutorials/05_admm_optimizer.ipynb
Labels: stable backport potential, automerge

#306 Pin sphinx-autodoc-typehints to unblock docs builds
  requirements-dev.txt
Labels: priority: high, stable backport potential, type: bug, automerge, type: ci

#308 Update docplex url
  qiskit_optimization/__init__.py
Labels: automerge

#310 A couple of minor improvements to docs/comments
  docs/tutorials/01_quadratic_program.ipynb
  qiskit_optimization/algorithms/admm_optimizer.py
  qiskit_optimization/converters/quadratic_program_to_qubo.py
Labels: automerge

#312 Fix copyright check when rebasing
  tools/check_copyright.py
Labels: stable backport potential, type: bug, automerge, type: ci

#309 Mention the remaining converters in the converters tutorial
  docs/tutorials/02_converters_for_quadratic_programs.ipynb
Labels: stable backport potential, automerge

#314 Correct the `ADMMOptimizer.get_compatibility_msg` docstring
  qiskit_optimization/algorithms/admm_optimizer.py
Labels: automerge

#318 Unpin networkx
  requirements.txt
Labels: automerge

#322 Update 08_cvar_optimization so that it works with Python 3.10
  docs/tutorials/08_cvar_optimization.ipynb
Labels: stable backport potential

#320 Add support for Python 3.10
  .github/workflows/main.yml
  pyproject.toml
  releasenotes/notes/add-python310-support-49aa9931cd4dabab.yaml
  setup.py
  tox.ini
Labels: type: enhancement

#324 Pin Windows CI version to 2019
  .github/actions/install-main-dependencies/action.yml
  .github/actions/install-optimization/action.yml
  .github/actions/run-tests/action.yml
  .github/workflows/main.yml
Labels: priority: high, type: ci
