Repository qiskit-community/qiskit-optimization, pull requests merged in 2022-04, with the labels that each got.

#357 Fix code example in ``RecursiveMinimumEigenOptimizer``
  qiskit_optimization/algorithms/recursive_minimum_eigen_optimizer.py
Labels: stable backport potential, type: documentation, automerge

#362 Set sphinx-build --keep-going by default
  .github/workflows/deploy-docs.yml
  .github/workflows/main.yml
  Makefile
  docs/Makefile
  tox.ini
Labels: type: documentation, type: enhancement

#361 Remove legacy providers interface
  qiskit_optimization/algorithms/grover_optimizer.py
  releasenotes/notes/basebackend-d32c42427b434739.yaml
Labels: priority: critical

#356 Fix `from_ising` with identity terms
  qiskit_optimization/translators/ising.py
  releasenotes/notes/fix-ising-9f8803b8a7a7e78b.yaml
  test/translators/test_ising.py
Labels: Changelog: Bugfix, automerge

#367 Cache Terra/Aer wheel files in the CI
  .github/actions/install-main-dependencies/action.yml
  .github/workflows/main.yml
Labels: type: enhancement, type: ci

#364 Finish the `RuntimeClient` -> `Client` rename
  qiskit_optimization/runtime/vqe_client.py
  releasenotes/notes/0.3/rename-runtime-program-9b1dbb897c49f5df.yaml
Labels: automerge

#368 Cache pip env.cache in the CI
  .github/workflows/main.yml
Labels: type: enhancement, automerge, type: ci
