Repository qiskit-community/qiskit-optimization, pull requests merged in 2022-05, with the labels that each got.

#365 Refactor the example in readme to remove networkx
  README.md
Labels: automerge

#369 Adds informative text formats to `repr` and `str` for problem related objects (part 2/3 refactor text representation of objects)
  .pylintdict
  qiskit_optimization/problems/linear_constraint.py
  qiskit_optimization/problems/linear_expression.py
  qiskit_optimization/problems/quadratic_constraint.py
  qiskit_optimization/problems/quadratic_expression.py
  qiskit_optimization/problems/quadratic_objective.py
  qiskit_optimization/problems/variable.py
  qiskit_optimization/translators/prettyprint.py
  releasenotes/notes/add-repr-str-9a33af0a6ffdca6e.yaml
  test/problems/test_linear_constraint.py
  test/problems/test_linear_expression.py
  test/problems/test_quadratic_constraint.py
  test/problems/test_quadratic_expression.py
  test/problems/test_quadratic_objective.py
  test/problems/test_variable.py
  test/translators/test_prettyprint.py
Labels: automerge

#372 Fix a few "typos" related to the Ising translator & its tests
  qiskit_optimization/translators/ising.py
  test/translators/test_ising.py
Labels: automerge

#371 Updates the link to the release planning
  CONTRIBUTING.md
Labels: automerge

#373 Add py.typed marker
  MANIFEST.in
  qiskit_optimization/py.typed
Labels: type: documentation, type: enhancement

#370 Refactor `repr` and `str` of `QuadraticProgram` and `OptimizationResult` (part 3/3 refactor text representation of objects)
  README.md
  docs/tutorials/01_quadratic_program.ipynb
  docs/tutorials/02_converters_for_quadratic_programs.ipynb
  docs/tutorials/03_minimum_eigen_optimizer.ipynb
  docs/tutorials/04_grover_optimizer.ipynb
  docs/tutorials/05_admm_optimizer.ipynb
  docs/tutorials/06_examples_max_cut_and_tsp.ipynb
  docs/tutorials/07_examples_vehicle_routing.ipynb
  docs/tutorials/08_cvar_optimization.ipynb
  docs/tutorials/09_application_classes.ipynb
  docs/tutorials/10_warm_start_qaoa.ipynb
  docs/tutorials/11_using_classical_optimization_solvers_and_models.ipynb
  docs/tutorials/12_qaoa_runtime.ipynb
  qiskit_optimization/algorithms/optimization_algorithm.py
  qiskit_optimization/problems/quadratic_program.py
  qiskit_optimization/translators/prettyprint.py
  releasenotes/notes/add-prettyprint-8ec601f41c9cc7d2.yaml
  releasenotes/notes/add-repr-str-qp-result-b2f9a423f60f2d13.yaml
  test/algorithms/test_optimization_result.py
  test/problems/test_quadratic_program.py
  test/test_readme_sample.py
  test/translators/test_prettyprint.py
Labels: Changelog: New feature, automerge

#375 Fix CI Terra/Aer build under MacOS
  .github/actions/install-main-dependencies/action.yml
Labels: type: ci
