Repository qiskit-community/qiskit-optimization, pull requests merged in 2022-10, with the labels that each got.

#423 Update Github Actions versions
  .github/actions/install-main-dependencies/action.yml
  .github/workflows/deploy-code.yml
  .github/workflows/deploy-docs.yml
  .github/workflows/main.yml
Labels: type: enhancement, type: ci

#422 Fix tsplib parser and added test
  .pylintdict
  qiskit_optimization/applications/tsp.py
  releasenotes/notes/fix-tsplib-parser-5ae73dc6233eed33.yaml
  test/applications/resources/test_tsplib.tsp
  test/applications/test_tsp.py
Labels: automerge

#424 Update CI actions/setup-python version
  .github/workflows/deploy-code.yml
  .github/workflows/deploy-docs.yml
  .github/workflows/main.yml
Labels: type: enhancement, automerge, type: ci
