Repository qiskit-community/qiskit-optimization, pull requests merged in 2023-09, with the labels that each got.

#542 Remove runtime program, quantum instance, and opflow
  docs/apidocs/qiskit_optimization.runtime.rst
  docs/migration/01_migration_guide_to_v0.5.ipynb
  docs/migration/01_migration_guide_to_v0.5.rst
  docs/tutorials/02_converters_for_quadratic_programs.ipynb
  docs/tutorials/03_minimum_eigen_optimizer.ipynb
  docs/tutorials/06_examples_max_cut_and_tsp.ipynb
  docs/tutorials/08_cvar_optimization.ipynb
  docs/tutorials/09_application_classes.ipynb
  docs/tutorials/12_qaoa_runtime.ipynb
  qiskit_optimization/__init__.py
  qiskit_optimization/algorithms/grover_optimizer.py
  qiskit_optimization/algorithms/minimum_eigen_optimizer.py
  qiskit_optimization/algorithms/optimization_algorithm.py
  qiskit_optimization/algorithms/warm_start_qaoa_optimizer.py
  qiskit_optimization/applications/graph_optimization_application.py
  qiskit_optimization/applications/optimization_application.py
  qiskit_optimization/problems/quadratic_program.py
  qiskit_optimization/runtime/__init__.py
  qiskit_optimization/runtime/qaoa_client.py
  qiskit_optimization/runtime/vqe_client.py
  qiskit_optimization/translators/ising.py
  releasenotes/notes/remove-quantum-instance-and-runtime-2c00393c0de1b9a9.yaml
  test/algorithms/legacy/__init__.py
  test/algorithms/legacy/test_min_eigen_optimizer.py
  test/algorithms/legacy/test_recursive_optimization.py
  test/algorithms/legacy/test_warm_start_qaoa.py
  test/algorithms/test_grover_optimizer.py
  test/algorithms/test_min_eigen_optimizer.py
  test/applications/test_optimization_application.py
  test/converters/test_converters.py
  test/runtime/__init__.py
  test/runtime/fake_vqeruntime.py
  test/runtime/test_qaoaclient.py
  test/runtime/test_vqeclient.py
  test/translators/test_ising.py
Labels: automerge

#544 Rotate poBranch deploy key
  tools/github_poBranch_update_key.enc
Labels: automerge

#543 Switch from qiskit-terra to qiskit
  .github/actions/install-main-dependencies/action.yml
  .github/workflows/deploy-docs.yml
  .github/workflows/main.yml
  CONTRIBUTING.md
  README.md
  docs/index.rst
  requirements.txt
  tox.ini
Labels: automerge

#548 Update Getting Started page
  docs/getting_started.rst
Labels: automerge

#537 Replace qiskit.algorithms with qiskit_algorithms
  .pylintdict
  README.md
  docs/conf.py
  docs/tutorials/01_quadratic_program.ipynb
  docs/tutorials/02_converters_for_quadratic_programs.ipynb
  docs/tutorials/03_minimum_eigen_optimizer.ipynb
  docs/tutorials/04_grover_optimizer.ipynb
  docs/tutorials/05_admm_optimizer.ipynb
  docs/tutorials/06_examples_max_cut_and_tsp.ipynb
  docs/tutorials/07_examples_vehicle_routing.ipynb
  docs/tutorials/08_cvar_optimization.ipynb
  docs/tutorials/09_application_classes.ipynb
  docs/tutorials/10_warm_start_qaoa.ipynb
  docs/tutorials/11_using_classical_optimization_solvers_and_models.ipynb
  qiskit_optimization/__init__.py
  qiskit_optimization/algorithms/admm_optimizer.py
  qiskit_optimization/algorithms/cobyla_optimizer.py
  qiskit_optimization/algorithms/cplex_optimizer.py
  qiskit_optimization/algorithms/grover_optimizer.py
  qiskit_optimization/algorithms/gurobi_optimizer.py
  qiskit_optimization/algorithms/minimum_eigen_optimizer.py
  qiskit_optimization/algorithms/optimization_algorithm.py
  qiskit_optimization/algorithms/recursive_minimum_eigen_optimizer.py
  qiskit_optimization/algorithms/scipy_milp_optimizer.py
  qiskit_optimization/algorithms/slsqp_optimizer.py
  qiskit_optimization/algorithms/warm_start_qaoa_optimizer.py
  qiskit_optimization/applications/tsp.py
  qiskit_optimization/converters/quadratic_program_converter.py
  qiskit_optimization/exceptions.py
  releasenotes/notes/switch-to-qiskit-algorithms-b0af38fe547bf5b5.yaml
  requirements.txt
  test/algorithms/test_grover_optimizer.py
  test/algorithms/test_min_eigen_optimizer.py
  test/algorithms/test_recursive_optimization.py
  test/algorithms/test_warm_start_qaoa.py
  test/converters/test_converters.py
Labels: automerge

#550 Remove deprecation.py
  qiskit_optimization/deprecation.py
  test/test_deprecation.py
Labels: automerge

#487 Integrate QRAO into Qiskit Optimization
  .pylintdict
  docs/apidocs/qiskit_optimization.algorithms.qrao.rst
  docs/explanations/aux_files/magic_state_rounding.svg
  docs/explanations/index.rst
  docs/explanations/qrao.rst
  docs/index.rst
  docs/tutorials/12_quantum_random_access_optimizer.ipynb
  qiskit_optimization/algorithms/__init__.py
  qiskit_optimization/algorithms/optimization_algorithm.py
  qiskit_optimization/algorithms/qrao/__init__.py
  qiskit_optimization/algorithms/qrao/encoding_commutation_verifier.py
  qiskit_optimization/algorithms/qrao/magic_rounding.py
  qiskit_optimization/algorithms/qrao/quantum_random_access_encoding.py
  qiskit_optimization/algorithms/qrao/quantum_random_access_optimizer.py
  qiskit_optimization/algorithms/qrao/rounding_common.py
  qiskit_optimization/algorithms/qrao/semideterministic_rounding.py
  releasenotes/notes/qrao-89d5ff1d2927de64.yaml
  test/algorithms/qrao/__init__.py
  test/algorithms/qrao/test_magic_rounding.py
  test/algorithms/qrao/test_quantum_random_access_encoding.py
  test/algorithms/qrao/test_quantum_random_access_optimizer.py
  test/algorithms/qrao/test_semideterministic_rounding.py
Labels: Changelog: New feature, automerge

#378 added some code and explanation for how solutions are interpreted using the interpret method, in the tutorial of converters
  docs/tutorials/02_converters_for_quadratic_programs.ipynb
Labels: automerge, Commmunity PR

#553 Fix a unit test error for Apple silicon
  test/algorithms/test_admm.py
Labels: automerge

#555 Fix a link to citation file
  README.md
Labels: automerge

#558 Minor fixes
  qiskit_optimization/algorithms/qrao/quantum_random_access_optimizer.py
  qiskit_optimization/algorithms/recursive_minimum_eigen_optimizer.py
  qiskit_optimization/algorithms/scipy_milp_optimizer.py
  qiskit_optimization/optionals.py
  requirements.txt
  test/algorithms/qrao/test_quantum_random_access_optimizer.py
  test/algorithms/test_scipy_milp_optimizer.py
Labels: automerge

#559 Fix stestr and mypy issues
  qiskit_optimization/applications/vehicle_routing.py
  requirements-dev.txt
Labels: automerge

#560 Fix a deprecation warning of matplotlib
  qiskit_optimization/applications/bin_packing.py
Labels: automerge
