Repository qiskit-community/qiskit-optimization, pull requests merged in 2023-01, with the labels that each got.

#460 Fix removed method from networkx
  docs/tutorials/06_examples_max_cut_and_tsp.ipynb
Labels: type: bug

#464 Fix Aer build error in CI
  .github/actions/install-main-dependencies/action.yml
Labels: priority: critical, type: ci

#466 Add missing items of `__all__`
  qiskit_optimization/algorithms/__init__.py
  qiskit_optimization/applications/__init__.py
Labels: automerge

#465 Update the minimum version of Qiskit Terra
  requirements.txt
Labels: automerge
