Repository qiskit-community/qiskit-optimization, pull requests merged in 2023-11, with the labels that each got.

#565 Update CI to use latest windows
  .github/actions/install-main-dependencies/action.yml
  .github/actions/install-optimization/action.yml
  .github/actions/run-tests/action.yml
  .github/workflows/main.yml
Labels: automerge

#566 Add Prelude 0.6
  docs/migration/01_migration_guide_to_v0.5.rst
  docs/migration/02_migration_guide_to_v0.6.rst
  docs/migration/index.rst
  releasenotes/notes/0.6-prelude-2740977b31d22583.yaml
  releasenotes/notes/switch-to-qiskit-algorithms-b0af38fe547bf5b5.yaml
Labels: automerge

#569 Improve documentation of INFINITY
  qiskit_optimization/__init__.py
  qiskit_optimization/infinity.py
Labels: stable backport potential, type: documentation, automerge

#571 Add code owners
  .github/CODEOWNERS
  .github/workflows/deploy-docs.yml
Labels: stable backport potential, automerge
