Repository qiskit-community/qiskit-optimization, pull requests merged in 2023-05, with the labels that each got.

#503 Terra main vs stable install switch
  .github/actions/install-main-dependencies/action.yml
  .github/workflows/main.yml
Labels: automerge, type: ci

#502 Update doc links and remove mailmap info from readme
  README.md
Labels: type: documentation, automerge

#507 Update mergify config
  .mergify.yml
Labels: type: ci

#505 Turn off CI for forks
  .github/workflows/main.yml
Labels: stable backport potential, automerge, type: ci

#504 Fix language toggle for docs
  docs/_templates/page.html
  docs/_templates/versions.html
  docs/conf.py
  docs/versionutils.py
  requirements-dev.txt
  tox.ini
Labels: stable backport potential, type: documentation, automerge

#496 Add ScipyMilpOptimizer
  .pylintdict
  qiskit_optimization/algorithms/__init__.py
  qiskit_optimization/algorithms/scipy_milp_optimizer.py
  qiskit_optimization/optionals.py
  releasenotes/notes/add-scipy-milp-7d78a5ae8c893cc5.yaml
  test/algorithms/test_scipy_milp_optimizer.py
Labels: Changelog: New feature, automerge, QAMP, Commmunity PR

#510 Remove unnecessary CSS files
  docs/_static/custom.css
  docs/_static/gallery.css
  docs/_static/style.css
  docs/conf.py
  docs/custom_directives.py
  requirements-dev.txt
Labels: stable backport potential, type: documentation, automerge

#514 Remove opflow in tutorials
  docs/tutorials/03_minimum_eigen_optimizer.ipynb
  docs/tutorials/06_examples_max_cut_and_tsp.ipynb
  docs/tutorials/08_cvar_optimization.ipynb
  docs/tutorials/09_application_classes.ipynb
Labels: type: documentation, automerge

#518 Upgrade to qiskit_sphinx_theme 1.12
  docs/_static/no_image.png
  docs/conf.py
  docs/custom_directives.py
  docs/getting_started.rst
  docs/versionutils.py
  pyproject.toml
  requirements-dev.txt
  tox.ini
Labels: stable backport potential, type: documentation, automerge

#521 Update tutorial 11 intro text around pip installed free solvers
  docs/tutorials/11_using_classical_optimization_solvers_and_models.ipynb
Labels: stable backport potential, type: documentation, automerge
