Repository qiskit-community/qiskit-optimization, pull requests merged in 2023-04, with the labels that each got.

#481 Add support for Python 3.11
  .github/workflows/main.yml
  releasenotes/notes/add-python311-support-b44aa96b718e7914.yaml
  setup.py
  tox.ini
Labels: automerge, type: ci

#490 Fix ``BackendV2`` support in runtime clients
  .pylintdict
  qiskit_optimization/runtime/vqe_client.py
  releasenotes/notes/runtimeclient-v2compat-c5b5541401cc6405.yaml
  test/algorithms/test_min_eigen_optimizer.py
Labels: Changelog: Bugfix, automerge

#489 Various docs changes for CI
  docs/conf.py
  requirements-dev.txt
  tox.ini
Labels: stable backport potential, type: documentation, automerge, type: ci

#492 Tag cell with nbsphinx-thumbnail
  docs/tutorials/06_examples_max_cut_and_tsp.ipynb
  docs/tutorials/07_examples_vehicle_routing.ipynb
  docs/tutorials/08_cvar_optimization.ipynb
  docs/tutorials/09_application_classes.ipynb
  docs/tutorials/10_warm_start_qaoa.ipynb
  docs/tutorials/12_qaoa_runtime.ipynb
Labels: stable backport potential, type: documentation, automerge

#467 Update `to_ising` and `from_ising` to support `SparsePauliOp`
  qiskit_optimization/algorithms/minimum_eigen_optimizer.py
  qiskit_optimization/algorithms/warm_start_qaoa_optimizer.py
  qiskit_optimization/problems/quadratic_program.py
  qiskit_optimization/translators/ising.py
  releasenotes/notes/support-sprase-pauli-op-00d29000d48c93ca.yaml
  test/converters/test_converters.py
  test/translators/test_ising.py
Labels: Changelog: New feature, automerge

#495 Deprecate `qiskit_optimization.runtime` module
  docs/tutorials/12_qaoa_runtime.ipynb
  qiskit_optimization/runtime/__init__.py
  qiskit_optimization/runtime/qaoa_client.py
  qiskit_optimization/runtime/vqe_client.py
  releasenotes/notes/deprecate-vqe-client-de93fff8c4645802.yaml
  test/runtime/test_qaoaclient.py
  test/runtime/test_vqeclient.py
Labels: Changelog: Deprecation, automerge

#497 Bump python version for CI check
  .github/actions/run-tests/action.yml
  .github/workflows/main.yml
Labels: automerge, type: ci

#498 Update legacy unit tests
  test/algorithms/legacy/__init__.py
  test/algorithms/legacy/test_min_eigen_optimizer.py
  test/algorithms/legacy/test_recursive_optimization.py
  test/algorithms/legacy/test_warm_start_qaoa.py
Labels: automerge

#499 Deprecates Opflow and `QuantumInstance`
  qiskit_optimization/algorithms/grover_optimizer.py
  qiskit_optimization/algorithms/minimum_eigen_optimizer.py
  qiskit_optimization/algorithms/optimization_algorithm.py
  qiskit_optimization/algorithms/warm_start_qaoa_optimizer.py
  qiskit_optimization/applications/optimization_application.py
  qiskit_optimization/translators/ising.py
  releasenotes/notes/deprecate-opflow-0c472adf38939a5c.yaml
  test/algorithms/legacy/test_min_eigen_optimizer.py
  test/algorithms/test_grover_optimizer.py
  test/algorithms/test_min_eigen_optimizer.py
  test/converters/test_converters.py
  test/problems/test_quadratic_program.py
  test/translators/test_ising.py
Labels: Changelog: Deprecation, automerge

#500 Pin ipython
  constraints.txt
Labels: type: ci
