Repository qiskit-community/qiskit-optimization, pull requests merged in 2023-03, with the labels that each got.

#474 Update slack invite link
  README.md
Labels: automerge

#478 Update deploy docs workflow and codeowners
  .github/CODEOWNERS
  .github/workflows/deploy-docs.yml
Labels: automerge

#480 Install Aer stable at CI
  .github/actions/install-main-dependencies/action.yml
Labels: type: ci

#482 Improving a sentence in getting_started.rst
  docs/getting_started.rst
Labels: stable backport potential, type: documentation, automerge

#475 Remove unnecessary `html_theme_path` option
  docs/conf.py
Labels: automerge

#483 deploy documentation in qiskit.org/ecosystem
  tools/deploy_documentation.sh
Labels: stable backport potential, type: documentation, automerge, type: ci

#485 Upgrade Pylint to 2.16.2
  .github/workflows/main.yml
  .pylintrc
  Makefile
  constraints.txt
  requirements-dev.txt
  setup.py
  test/translators/test_docplex_mp.py
  tools/check_copyright.py
Labels: automerge, type: ci
