Repository qiskit-community/qiskit-optimization, pull requests merged in 2024-02, with the labels that each got.

#595 Update actions using deprecated Node.js
  .github/actions/install-main-dependencies/action.yml
  .github/workflows/deploy-code.yml
  .github/workflows/deploy-docs.yml
  .github/workflows/main.yml
Labels: stable backport potential, automerge, type: ci

#598 Update intersphinx links and others
  README.md
  docs/conf.py
  docs/index.rst
  docs/migration/02_migration_guide_to_v0.6.rst
  docs/tutorials/08_cvar_optimization.ipynb
  docs/tutorials/12_quantum_random_access_optimizer.ipynb
  qiskit_optimization/__init__.py
  setup.py
Labels: stable backport potential, type: documentation, automerge

#596 Add dependabot to manage future Github Actions updates
  .github/dependabot.yml
Labels: automerge, type: ci

#592 Update CPLEX-incompatible Python version in documentation
  README.md
  docs/getting_started.rst
Labels: stable backport potential, type: documentation

#602 Bump Mac and Win upper Python version for CI
  .github/workflows/main.yml
Labels: stable backport potential, type: ci

#604 Remove qiskit.org links
  CONTRIBUTING.md
  docs/getting_started.rst
  docs/migration/01_migration_guide_to_v0.5.rst
  docs/tutorials/12_quantum_random_access_optimizer.ipynb
  setup.py
Labels: stable backport potential, type: documentation

#605 Remove qiskit.org links from release notes
  releasenotes/notes/0.5/add-primitives-support-31af39549b5e66e3.yaml
  releasenotes/notes/0.6/0.6-prelude-2740977b31d22583.yaml
  releasenotes/notes/0.6/switch-to-qiskit-algorithms-b0af38fe547bf5b5.yaml
Labels: automerge

#607 Remove all other languages other than Spanish and Japanese
  docs/conf.py
Labels: stable backport potential, type: documentation

#610 Fix tutorials to work with Qiskit 1.0
  docs/tutorials/01_quadratic_program.ipynb
  docs/tutorials/02_converters_for_quadratic_programs.ipynb
  docs/tutorials/03_minimum_eigen_optimizer.ipynb
  docs/tutorials/04_grover_optimizer.ipynb
  docs/tutorials/05_admm_optimizer.ipynb
  docs/tutorials/06_examples_max_cut_and_tsp.ipynb
  docs/tutorials/07_examples_vehicle_routing.ipynb
  docs/tutorials/08_cvar_optimization.ipynb
  docs/tutorials/09_application_classes.ipynb
  docs/tutorials/10_warm_start_qaoa.ipynb
  docs/tutorials/11_using_classical_optimization_solvers_and_models.ipynb
  docs/tutorials/12_quantum_random_access_optimizer.ipynb
  docs/tutorials/tutorial_magics.py
Labels: stable backport potential, type: documentation, automerge

#580 Add Python 3.12 support
  .github/workflows/main.yml
  releasenotes/notes/add-python312-support-e3e2bc0c6a10b613.yaml
  setup.py
  tox.ini
Labels: stable backport potential

#614 [Stable] Prepare 0.6.1 release
  qiskit_optimization/VERSION.txt
Labels: automerge
