Repository qiskit-community/qiskit-optimization, pull requests merged in 2024-08, with the labels that each got.

#630 Pin pip for "pip check"
  .github/workflows/main.yml
Labels: stable backport potential, type: ci

#629 Unpin numpy
  requirements.txt
  test/algorithms/qrao/test_quantum_random_access_optimizer.py
Labels: stable backport potential, automerge

#627 Fix incorrect decoding of decision variables by ``MagicRounding``
  qiskit_optimization/algorithms/qrao/magic_rounding.py
  releasenotes/notes/fix-qrao-d0402da6a5c40121.yaml
  test/algorithms/qrao/test_magic_rounding.py
Labels: Changelog: Bugfix, stable backport potential, automerge
